wecode-bootcamp-korea/49-2nd-we4meat-frontend

src/components/Input/Input.jsx, src/components/Input/Input.scss, src/pages/Main/Main.js
- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?
(예시) 고객의 유입과 전환을 책임지는 회원 기능에서, 유저의 이탈을 방지하기 위해 input 창 바로 아래에서 실시간으로 적색의 경고 메세지를 전달 받습니다.
- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?
(예시) 유저는 실시간으로 스스로 오기입한 내용을 확인할 수 있기 때문에 잘못 계정 정보를 작성함으로써 발생될 수 있는 변수를 최소화할 수 있습니다. 이는 곧 유저 전환의 허들을 낮추어 줄 수 있습니다.
<br />
(예시) 로그인 기능 추가
- (예시) email입력 `@`필요,password에 숫자로 8자이상 유효성 검사 추가
- (예시) 유효성 검사 통과시 버튼 컬러 변경 및 버튼 활성화
<br />
<br />
-
<br />
- (예시) 새로운 배열메서드 filter를 쓸 수 있게됐습니다.
- (예시) 상수데이터와 map 메서드로 반복되는 UI를 그릴 수 있게 됐습니다.
- (예시) fetch함수를 어떻게 쓰는지 알게됐습니다.
- (예시) 계산된 속성명 (computed property)을 쓰긴했는데 어떻게 돌아가는지 이해가 잘 안되서
블로그에 정리해봐야겠습니다.
- (예시) 화살표 함수(arrow-function) 어떤 코드를 언제 생략할 수있는지 완벽 이해했습니다.
- (예시) 구조분해할당(Destructuring assignment)을 써보니 가독성도, 유지보수도 편할것같습니다.
<br />
=> [style] input 컴포넌트 UI구현

src/components/Checkbox/Checkbox.js, src/components/Checkbox/Checkbox.scss, src/components/Radio/Radio.js, src/components/Radio/Radio.scss, src/components/RadioGroup/RadioGroup.js, src/components/RadioGroup/RadioGroup.scss, src/data/deliveryData.js, src/styles/base/common.scss, src/styles/partials/theme.scss
- 추후 라디오 그룹에서의 props 정리가 필요함
- value, text, defaultChecked의 값도 부모 컴포넌트에서 자유롭게 내려줄 수 있어야 함
=> [Style] 체크박스, 라디오, 라디오 그룹 컴포넌트 개발

src/styles/layout/layout.scss, src/styles/partials/mixin.scss
- 래핑된 레이아웃 추가: inner-wrap 클래스 사용
- 그리드 시스템 추가: @include GridSystem() 사용
=> [style] 공통 레이아웃 개발

src/Router.js, src/components/Button/Button.js, src/components/Button/Button.scss, src/components/Checkbox/Checkbox.js, src/components/Checkbox/Checkbox.scss, src/components/Event/Event.js, src/components/Header/Header.js, src/components/Header/Header.scss, src/components/Header/LinkGoIcon/LinkGoIcon.scss, src/components/Header/LoginItemGroup/LoginItemGroup.scss, src/components/Header/SubNav/SubNav.js, src/components/Header/SubNav/SubNav.scss, src/components/Input/Input.scss, src/components/Radio/Radio.js, src/components/Radio/Radio.scss, src/components/RadioGroup/RadioGroup.scss, src/pages/Login/Login.scss, src/pages/Main/Main.js, src/pages/Main/Main.scss, src/styles/base/common.scss, src/styles/partials/theme.scss
=> [fix] 글로벌 테마 수정

src/components/Input/Input.js, src/components/Input/Input.scss
- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?
(예시) 고객의 유입과 전환을 책임지는 회원 기능에서, 유저의 이탈을 방지하기 위해 input 창 바로 아래에서 실시간으로 적색의 경고 메세지를 전달 받습니다.
- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?
(예시) 유저는 실시간으로 스스로 오기입한 내용을 확인할 수 있기 때문에 잘못 계정 정보를 작성함으로써 발생될 수 있는 변수를 최소화할 수 있습니다. 이는 곧 유저 전환의 허들을 낮추어 줄 수 있습니다.
<br />
(예시) 로그인 기능 추가
- (예시) email입력 `@`필요,password에 숫자로 8자이상 유효성 검사 추가
- (예시) 유효성 검사 통과시 버튼 컬러 변경 및 버튼 활성화
<br />
<br />
-
<br />
- (예시) 새로운 배열메서드 filter를 쓸 수 있게됐습니다.
- (예시) 상수데이터와 map 메서드로 반복되는 UI를 그릴 수 있게 됐습니다.
- (예시) fetch함수를 어떻게 쓰는지 알게됐습니다.
- (예시) 계산된 속성명 (computed property)을 쓰긴했는데 어떻게 돌아가는지 이해가 잘 안되서
블로그에 정리해봐야겠습니다.
- (예시) 화살표 함수(arrow-function) 어떤 코드를 언제 생략할 수있는지 완벽 이해했습니다.
- (예시) 구조분해할당(Destructuring assignment)을 써보니 가독성도, 유지보수도 편할것같습니다.
<br />
=> [fix][style] input props className 지정 값 수정 및 스타일 수정

src/components/Button/Button.js
=> [etc]컴포넌트 사용 방법 주석추가

src/components/Checkbox/Checkbox.js, src/components/Radio/Radio.js, src/components/RadioGroup/RadioGroup.js
- 체크박스 컴포넌트 사용법 주석
- 라디오 컴포넌트 사용법 주석
- 라디오그룹 컴포넌트 사용법 주석
=> [fix] 개인 작업 컴포넌트 사용법 주석

src/components/ProductContent/ProductContent.js, src/components/ProductContent/ProductContent.scss
ProductContent 컴포넌트 사용법 클래스네임 (inventory)추가
상품준비중 스타일 추가
=> [fix][style] 컴포넌트 사용법 수정 및 상품준비중 스타일 추가

src/components/Input/Input.js, src/components/Input/Input.scss
input 컴포넌트 props 변수 사용하던 것을 매개변수 자리로 이동
label 태그에 클래스 부여 후 네스팅작업
=> [fix]input 컴포넌트 props 수정 및 scss nesting작업

src/components/Input/Input.js
=> [fix]Input 컴포넌트 사용법 내용 추가

src/Router.js, src/components/EasyLogin/EasyLogin.js, src/pages/Login/Login.js, src/pages/Mypage/Mypage.js, src/pages/Mypage/Mypage.scss
=> [fix] main id 적용

src/Router.js, src/components/Header/Header.js, src/components/SkipNavigation/SkipNavigation.js, src/components/SkipNavigation/SkipNavigation.scss, src/pages/Main/Main.js
- 웹 접근성 처리를 위해 스킵 네비게이션 적용(main only)
=> [feat] 스킵 네비게이션 적용

public/data/responseData.json, src/components/EasyLogin/EasyLogin.js, src/components/EasyLogin/EasyLogin.scss, src/components/Input/Input.scss, src/components/OptionalNotice/OptionalNotice.js, src/components/OptionalNotice/OptionalNotice.scss, src/components/PageTitle/PageTitle.js, src/pages/Login/Login.js, src/pages/Login/LoginForm/LoginForm.js
- 로그인 프로세스 로직 개발 완료
- 모조 응답 데이터 작성
- 각 버튼 또는 링크의 path는 논의 후 수정 예정
=> [Feature] 로그인 화면 개발

public/data/mock.json, src/components/BestTitle/BestTitle.js, src/components/BestTitle/BestTitle.scss, src/components/Product/Product.scss, src/components/ProductContent/ProductContent.js, src/components/ProductListImg/ProductImg.js, src/components/ProductText/ProductText.js, src/components/ProductTitle/ProductTitle.js, src/components/Products/Products.js, src/components/Products/Products.scss
1. 상품준비중 구현완료
2. 무항생제 태그 구현완료
3. 레이아웃 수정 완료
=> [feat] products컴포넌트 조립 완료

src/components/CartButton/CartButton.scss, src/components/Product/Product.js, src/components/ProductListImg/ProductImg.js, src/components/ProductListImg/ProductImg.scss, src/components/Products/Products.js
1. className undefined 발생 오류 수정
2. link 태그 display속성 수정
3. 장바구니 hover style 수정
=> [fix] class undefined오류 수정 및 장바구니 hover 스타일 수정

src/Router.js, src/components/Footer/Footer.scss
=> [style] 푸터 ui 수정

src/Router.js, src/components/InitializeScroll/InitializeScroll.js
- spa인 react에서 페이지 이동 시 전 단계의 스크롤을 기억합니다. 따라서 초기화하는 로직을 하나 추가했습니다.
=> [feat] react 페이지 이동 시 스크롤 초기화 개발

src/components/CategoryTab/CategoryTab.js
=> [fix]쿼리스트링 초기값 설정

src/pages/Cart/Cart.js
=> [style]장바구니 수량 변경 ui 적용 완료

public/data/ReviewMock.json, src/components/CategoryTab/CategoryTab.scss, src/components/Modal/ModalContent/CartModal.js, src/pages/Detail/Detail.scss, src/styles/base/common.scss
- 컨텐츠가 뷰포트를 채우지 못했을 경우를 상정하여 레이아웃 수정
- 카테고리 탭의 커서 포인트 처리
=> [fix] 레이아웃 수정 및 마이너 이슈 처리

src/pages/SignUp/SignUp.js, src/pages/SignUp/SignUp.scss, src/pages/SignUp/UserInfo/UserInfo.js, src/pages/SignUp/UserInfo/UserInfo.scss
회원가입 페이지 구현완료
1. 유효성검사
2. validation 적용
3. 휴대폰번호 로직 구현
=> [feat] 회원가입 페이지 구현 완료

src/components/BestTitle/BestTitle.js, src/components/Modal/ModalContent/ReviewCreateModal.js, src/components/Products/Products.js, src/components/Review/Review.js, src/config.js, src/pages/Detail/Detail.js, src/pages/List/List.js, src/pages/Login/LoginForm/LoginForm.js, src/pages/Main/ListBanner/ListBanner.js
- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?
(예시) 고객의 유입과 전환을 책임지는 회원 기능에서, 유저의 이탈을 방지하기 위해 input 창 바로 아래에서 실시간으로 적색의 경고 메세지를 전달 받습니다.
- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?
(예시) 유저는 실시간으로 스스로 오기입한 내용을 확인할 수 있기 때문에 잘못 계정 정보를 작성함으로써 발생될 수 있는 변수를 최소화할 수 있습니다. 이는 곧 유저 전환의 허들을 낮추어 줄 수 있습니다.
<br />
(예시) 로그인 기능 추가
- (예시) email입력 `@`필요,password에 숫자로 8자이상 유효성 검사 추가
- (예시) 유효성 검사 통과시 버튼 컬러 변경 및 버튼 활성화
<br />
<br />
-
<br />
- (예시) 새로운 배열메서드 filter를 쓸 수 있게됐습니다.
- (예시) 상수데이터와 map 메서드로 반복되는 UI를 그릴 수 있게 됐습니다.
- (예시) fetch함수를 어떻게 쓰는지 알게됐습니다.
- (예시) 계산된 속성명 (computed property)을 쓰긴했는데 어떻게 돌아가는지 이해가 잘 안되서
블로그에 정리해봐야겠습니다.
- (예시) 화살표 함수(arrow-function) 어떤 코드를 언제 생략할 수있는지 완벽 이해했습니다.
- (예시) 구조분해할당(Destructuring assignment)을 써보니 가독성도, 유지보수도 편할것같습니다.
<br />
=> [fix] API 통신 테스트

src/components/Header/LoginItemGroup/LoginItemGroup.js, src/components/Products/Products.js, src/config.js, src/pages/Login/LoginForm/LoginForm.js, src/pages/SignUp/SignUp.js, src/pages/SignUp/UserInfo/UserInfo.js
- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?
(예시) 고객의 유입과 전환을 책임지는 회원 기능에서, 유저의 이탈을 방지하기 위해 input 창 바로 아래에서 실시간으로 적색의 경고 메세지를 전달 받습니다.
- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?
(예시) 유저는 실시간으로 스스로 오기입한 내용을 확인할 수 있기 때문에 잘못 계정 정보를 작성함으로써 발생될 수 있는 변수를 최소화할 수 있습니다. 이는 곧 유저 전환의 허들을 낮추어 줄 수 있습니다.
<br />
(예시) 로그인 기능 추가
- (예시) email입력 `@`필요,password에 숫자로 8자이상 유효성 검사 추가
- (예시) 유효성 검사 통과시 버튼 컬러 변경 및 버튼 활성화
<br />
<br />
-
<br />
- (예시) 새로운 배열메서드 filter를 쓸 수 있게됐습니다.
- (예시) 상수데이터와 map 메서드로 반복되는 UI를 그릴 수 있게 됐습니다.
- (예시) fetch함수를 어떻게 쓰는지 알게됐습니다.
- (예시) 계산된 속성명 (computed property)을 쓰긴했는데 어떻게 돌아가는지 이해가 잘 안되서
블로그에 정리해봐야겠습니다.
- (예시) 화살표 함수(arrow-function) 어떤 코드를 언제 생략할 수있는지 완벽 이해했습니다.
- (예시) 구조분해할당(Destructuring assignment)을 써보니 가독성도, 유지보수도 편할것같습니다.
<br />
=> [hotfix] api 통신 진행 중

src/components/Header/LoginItemGroup/LoginItemGroup.js
=> [style]header/login 상태 ui 변환

src/Router.js, src/components/Header/Header.js, src/components/Header/LoginItemGroup/LoginItemGroup.js, src/components/Header/SubNav/SubNav.js, src/pages/Login/Login.js, src/pages/Login/LoginForm/LoginForm.js
로그인시 haeader에 마이페이지로 ui 변화와 sidenav 마이페이지 활성화
=> [fix]header/sidenav login상태 ui 변화 구현

src/components/CategoryTab/CategoryTab.js, src/components/Modal/ModalContent/CartModal.js, src/components/Modal/ModalContent/ChargeModal.js, src/config.js, src/pages/Cart/Cart.js, src/pages/Pay/Pay.js, src/pages/Pay/PayCoupon/CouponBox/CouponBox.js, src/pages/Pay/PayCoupon/PayCoupon.js, src/pages/Pay/PayLast/PayLast.js
=> [feat]API 통신2

src/components/Modal/ModalContent/ChargeModal.js, src/pages/Pay/Pay.js, src/pages/Pay/PayCoupon/PayCoupon.js, src/pages/Pay/PayLast/PayBox/PayBox.js, src/pages/Pay/PayLast/PayLast.js
=> [feat]API통신 연결 5

src/components/Modal/Modal.js, src/components/Modal/ModalContent/CartModal.js, src/components/Modal/ModalContent/ChargeModal.js, src/components/Modal/ModalContent/ReviewCreateModal.js, src/components/Review/Review.js, src/pages/Cart/Cart.js, src/pages/Detail/Detail.js, src/pages/Order/Order.js, src/pages/Pay/Pay.js, src/pages/Pay/PayCoupon/PayCoupon.js, src/pages/Pay/PayLast/PayLast.js, src/pages/SignUp/UserInfo/UserInfo.js
=> [etc]console code 삭제
